# SonarCloud configuration for yamllint-config-nick2bad4u.
sonar.organization=nick2bad4u
sonar.projectKey=Nick2bad4u_yamllint-config-nick2bad4u
sonar.projectName=yamllint-config-nick2bad4u
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
